language: c

sudo: false

matrix:
  include:
    - os: linux
      addons:
        apt:
          packages: [ 'protobuf-compiler', 'libprotobuf-dev' ]
    - os: osx


install:
 - if [[ $(uname -s) == 'Darwin' ]]; then brew install protobuf; fi;
 - make

script:
 - echo '{"type":"Feature","properties":{},"geometry":{"type":"Point","coordinates":[0,0]}}' > test.json
 - ./tippecanoe -o test.mbtiles test.json
