language: generic

sudo: false

matrix:
  include:
    - os: linux
      compiler: gcc
      env: COVERAGE=gcov-4.9 CC="gcc-4.9" CXX="g++-4.9"
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: [ 'g++-4.9' ]
    - os: linux
      compiler: clang
      env: CC="clang-3.5" CXX="clang++-3.5"
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.5' ]
          packages: [ 'clang-3.5' ]
    - os: osx
      compiler: clang


install:
 - if [ -n "${COVERAGE}" ]; then
       export CXXFLAGS="--coverage -g";
       export CFLAGS="--coverage -g";
       export LDFLAGS="--coverage";
   fi;
 - make

script:
 - make test
 - if [ -n "${COVERAGE}" ]; then
       rm vector_tile.pb.o;
       ${COVERAGE} -lp *.o;
       pip install --user cpp-coveralls;
       ~/.local/bin/coveralls --no-gcov -i ./ --exclude clipper --exclude vector_tile.pb.cc --exclude vector_tile.pb.h;
   fi
